//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioPlayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSong
    {
        public int SongID { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public Nullable<int> Duration_s { get; set; }
        public Nullable<bool> Logged { get; set; }
    }
}
